apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: network-gcp-demo
  labels:
    provider: GCP
    resourcetype: network
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingMode: "REGIONAL"
  providerConfigRef:
    name: gcp-config
