apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    provider: GCP
    resourcetype: instance
  name: instance-gcp-demo
  annotations:
     crossplane.io/paused: "false"
spec:
  forProvider:
    machineType: e2-medium
    zone: europe-west6-a
    bootDisk: 
      - initializeParams:
        - image: debian-cloud/debian-11
    networkInterface: 
      - network: network-gcp-demo
        subnetwork: subnet-gcp-demo
  providerConfigRef:
    name: gcp-config
