# Family Providers GCP
# apiVersion: pkg.crossplane.io/v1
# kind: Provider
# metadata:
#   name: provider-family-gcp
# spec:
#   package: xpkg.upbound.io/upbound/provider-family-gcp:v0.36.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-container
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-container:v0.36.0

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-compute
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-compute:v0.36.0

---

# Entire Provider GCP
# apiVersion: pkg.crossplane.io/v1
# kind: Provider
# metadata:
#   name: provider-gcp
#   labels:
#     provider: GCP
#     resourcetype: provider
# spec:
#   package: xpkg.upbound.io/upbound/provider-gcp:v0.32.0